version: '3.8'

services:
  # Test Database
  test-db:
    image: postgres:17
    environment:
      POSTGRES_DB: test_cstatsentry
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_cstatsentry"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Test Redis
  test-redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - test_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Mock Steam API
  mock-steam-api:
    build: ./mock-services/steam-api
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mock-services/steam-api:/app
    restart: unless-stopped

volumes:
  test_postgres_data:
  test_redis_data: