"""add_steam_sharecode_fields_to_user

Revision ID: 8d775ee192b7
Revises: 001
Create Date: 2025-09-30 16:32:36.114588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d775ee192b7'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes if they exist (skip errors if they don't)
    try:
        op.drop_index('ix_matches_user_date', table_name='matches')
    except Exception:
        pass

    try:
        op.drop_index('ix_analyses_score', table_name='player_analyses')
    except Exception:
        pass

    # Convert ARRAY to JSON with explicit casting
    op.alter_column('players', 'previous_names',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='previous_names::text::json')

    try:
        op.drop_index('ix_teammates_user', table_name='user_teammates')
    except Exception:
        pass

    # Add sharecode fields to users table
    op.add_column('users', sa.Column('steam_auth_code', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_match_sharecode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_match_sharecode')
    op.drop_column('users', 'steam_auth_code')
    op.create_index(op.f('ix_teammates_user'), 'user_teammates', ['user_id', 'last_seen'], unique=False)
    op.alter_column('players', 'previous_names',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.create_index(op.f('ix_analyses_score'), 'player_analyses', ['suspicion_score'], unique=False)
    op.create_index(op.f('ix_matches_user_date'), 'matches', ['user_id', 'match_date'], unique=False)
    # ### end Alembic commands ###